[flint]
version = 1
plugins_branch = "locust"

[tests.locust]
script = "run.sh"
locustfile = "locustfile.py"
users = 100
spawn_rate = 10
run_time = "20s"
host = "http://127.0.0.1:8000"
output_path = "reports"

[report.json]
output_path = "reports"
