[project]
authors = ["Soham Karandikar <sohamk10@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "locust"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
locust = ">=2.33.2, <3"
